version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8888:8888"  # 호스트 포트:컨테이너 포트
    volumes:
      - ../logs:/app/backend/logs

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:8080"  # 호스트 포트:컨테이너 포트
    volumes:
      - ../logs:/app/frontend/logs 