FROM python:3-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl tar
RUN curl -L -O https://github.com/annmunju/sesac-semi-01/raw/refs/heads/main/frontend.tar
RUN mkdir -p /app/frontend && tar -xvf frontend.tar -C /app/frontend
RUN mkdir -p /app/frontend/logs

WORKDIR /app/frontend
VOLUME ["/app/frontend/logs"]
EXPOSE 8080
RUN chmod +x start_demo.sh

CMD ["bash", "start_demo.sh"]