FROM python:3-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl tar

RUN curl -L -O https://github.com/annmunju/sesac-semi-01/raw/refs/heads/main/backend.tar
RUN mkdir -p /app/backend && tar -xvf backend.tar -C /app/backend

WORKDIR /app/backend

VOLUME ["/app/backend/logs"]

EXPOSE 8888

CMD ["bash", "start_api.sh"]